version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-chat-bot
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama-chat-ui:latest
    container_name: ollama-chat-ui
    depends_on:
      - ollama
    ports:
      - "8502:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama_data:
